name: Build PiKVM NanoPi Neo2


on:
  workflow_dispatch:


permissions:
  contents: write


env:

  # NanoPi Neo2
  BOARD: nanopineo2

  # 老板稳定内核
  BRANCH: legacy

  # Debian 系
  RELEASE: bookworm

  BUILD_MINIMAL: no
  BUILD_DESKTOP: no
  KERNEL_CONFIGURE: no


jobs:


  build:


    runs-on: ubuntu-22.04


    steps:


    # 拉取你的 PiKVM_NanoPi-Neo2 仓库
    - name: Checkout
      uses: actions/checkout@v4



    # ARM64 模拟支持
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3



    - name: Prepare host
      run: |

        sudo apt update

        sudo apt install -y \
          git \
          wget \
          curl \
          jq \
          aria2



    # 固定 Armbian build 版本
    - name: Download Armbian build
      run: |


        git clone \
          --depth=1 \
          --branch v24.2.3 \
          https://github.com/armbian/build.git \
          build



    # 注入你的 PiKVM 安装脚本
    - name: Copy customize-image.sh
      run: |


        mkdir -p build/userpatches


        cp \
          userpatches/customize-image.sh \
          build/userpatches/customize-image.sh


        chmod +x \
          build/userpatches/customize-image.sh



    # 编译
    - name: Build NanoPi Neo2
      id: build
      run: |


        cd build


        ./compile.sh build \
          BOARD=${BOARD} \
          BRANCH=${BRANCH} \
          RELEASE=${RELEASE} \
          BUILD_MINIMAL=${BUILD_MINIMAL} \
          BUILD_DESKTOP=${BUILD_DESKTOP} \
          KERNEL_CONFIGURE=${KERNEL_CONFIGURE}



        echo "status=success" >> $GITHUB_OUTPUT




    # 打包
    - name: Pack image
      if: steps.build.outputs.status == 'success'
      run: |


        cd build/output/images


        tar -Jcvf \
          /tmp/nanopi_neo2_pikvm.tar.xz \
          *.img




    # Actions附件
    - name: Upload artifact
      if: steps.build.outputs.status == 'success'
      uses: actions/upload-artifact@v4


      with:

        name: NanoPi-Neo2-PiKVM

        path: /tmp/nanopi_neo2_pikvm.tar.xz




    # Release
    - name: Release image
      if: steps.build.outputs.status == 'success'
      uses: softprops/action-gh-release@v2


      with:

        tag_name: nano-${{ github.run_number }}

        files: /tmp/nanopi_neo2_pikvm.tar.xz


      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
